export const defaultFeatures = [
  "Heated Seats",
  "Central Door Locking",
  "Air Bag Driver",
  "Air Bag Passenger",
  "Air Bag Side",
  "Anti-Lock Brakes",
  "Centre Console",
  "Centre Rear Seat Belt",
  "Child Locks",
  "Cruise Control",
  "Satellite Navigation",
  "Start/Stop System",
  "Tinted Windows",
  "Upholstery Cloth",
  "Upholstery Leather",
  "Touch Screen",
  "Spare Tyre",
  "Type Pressure Control",
  "Tyre Repair Kit",
  "Immobiliser",
  "Cup Holders",
];
